substitutions:
  devicename: blanc

esphome:
  name: ${devicename}
  on_boot:
    priority: -100
    then:
      - light.turn_on:
          id: statusledlight
          brightness: 15%
          red: 0%
          green: 100%
          blue: 0%
      - delay: 10s
      - light.turn_off: statusledlight
#  includes:
#    - lgtv_uart.h

esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf

api:
  services:
    - service: brigthness
      variables:
        value: int
      then:
        - uart.write:
            id: lgtv_serial_interface
            data: !lambda |-
              char output[9];  // Max buffer size (including null terminator)
              int chars_written = snprintf(output, sizeof(output), "mg 1 %02x\r", value);
              std::vector<uint8_t> vec(output, output + sizeof(output) - 1);
              return vec;
    - service: write
      variables:
        command: string
      then:
        - uart.write:
            id: lgtv_serial_interface
            data: !lambda |-
              std::string str = command;
              str += "\r";
              std::vector<uint8_t> vec(str.begin(), str.end());
              return vec;

logger:
  baud_rate: 0
  level: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome
  password: !secret ota_password

light:
  - platform: esp32_rmt_led_strip
    name: "Status LED"
    rgb_order: GRB
    chipset: ws2812
    pin: 7
    num_leds: 1
    id: statusledlight
    icon: "mdi:led-outline"



uart:
  id: lgtv_serial_interface
  baud_rate: 9600
  tx_pin: 20
  rx_pin: 21
    # debug:

switch:
  - platform: gpio
    pin:
      number: GPIO5
      mode:
        output: true
        pulldown: true
    name: "TV arm relay retract"
    id: "blanc_relay_retract"
    restore_mode: always_off
  - platform: gpio
    pin:
      number: GPIO4
      mode:
        output: true
        pulldown: true
    name: "TV arm relay expand"
    id: "blanc_relay_expand"
    restore_mode: always_off

sensor:
  - platform: adc
    device_class: current #0.015~ 0.020 @ 0.11A ; 0.19 @ 1A ; 1.01 1.06 : 0.15 0.18V
    pin: GPIO1
    id: "blanc_tvarm_current"
    internal: true
    unit_of_measurement: A
    update_interval: 200ms
    on_value:
      then:
        - lambda: |-
            auto call = id(statusledlight).turn_on();
            if (id(blanc_relay_expand).state || id(blanc_relay_retract).state) {
              float r, g, b;
              b = 0.0;
              float current = x;
              if (current > 1.5) { current = 1.5; }
              if (current < 0) { current = 0; }

              if (current <= 0.75) {
                r = current / 0.75;
                g = 1.0;
              } else {
                r = 1.0;
                g = 1.0 - ((current - 0.75) / 0.75) * (1.0 - 0.55);
              }

              call.set_red(r);
              call.set_green(g);
              call.set_blue(b);
              call.set_brightness(0.40);
              call.perform();
            } else {
              id(statusledlight).turn_off().perform();
            }
    filters:
    - sliding_window_moving_average:
        window_size: 10
        send_every: 10
    - multiply: 4.5
  - platform: adc
    pin: GPIO3
    name: "Monitor brightness dial"
    id: "monitor_brightness_dial"
    update_interval: 50ms
    raw: true
    unit_of_measurement: "%"
    filters:
    - sliding_window_moving_average:
        window_size: 8
        send_every: 8
    - lambda: |-
        if ( x < 500) { return 1 ; }
        if ( x < 1000) { return 4 ; }
        if ( x < 1500) { return 8 ; }
        if ( x < 2000) { return 16 ; }
        if ( x < 2500) { return 20 ; }
        if ( x < 3000) { return 40 ; }
        if ( x < 3500) { return 80 ; }
        return 100 ;

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO6
      mode:
        input: true
        pulldown: true
    id: "blanc_button_red"
    name: "blanc_button_red"
    on_press:
      - cover.stop: blanc_tvarm_arm

  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pulldown: true
    id: "blanc_button_yellow"
    name: "blanc_button_yellow"

  - platform: gpio
    pin:
      number: GPIO8
      inverted: true
    id: "blanc_arm_switch_right"
    name: "blanc_arm_switch_right"
    on_press:
      then:
        - cover.open: blanc_tvarm_arm
  - platform: gpio
    pin:
      number: GPIO2
      inverted: true
    id: "blanc_arm_switch_left"
    name: "blanc_arm_switch_left"
    on_press:
      then:
        - cover.close: blanc_tvarm_arm


cover:
  - platform: current_based
    name: "Blanc TV arm"
    id: "blanc_tvarm_arm"

    open_sensor: blanc_tvarm_current
    open_moving_current_threshold: 0.2
    open_obstacle_current_threshold: 1.5
    open_duration: 85s
    open_action:
      - switch.turn_on: blanc_relay_expand

    close_sensor: blanc_tvarm_current
    close_moving_current_threshold: 0.2
    close_obstacle_current_threshold: 1.3
    close_duration: 85s
    close_action:
      - switch.turn_on: blanc_relay_retract

    stop_action:
      - switch.turn_off: blanc_relay_expand
      - switch.turn_off: blanc_relay_retract

    obstacle_rollback: 3%
    start_sensing_delay: 2s
    malfunction_detection: False
