esphome:
  name: fan-kitchen

esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf
    version: recommended
  variant: esp32c3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  safe_mode: true
  password: !secret ota_password

mqtt:
  broker: !secret mqtt_broker_ip

api:

logger:


