substitutions:
  device_upper: LOLIN C3 MINI
  device_name: fan-kitchen

esphome:
  name: ${device_name}
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: lolin_c3_mini
  variant: esp32c3
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  safe_mode: true
  password: !secret ota_password

mqtt:
  broker: !secret mqtt_broker_ip

api:

logger:

network:
  enable_ipv6: true

text_sensor:
- platform: template
  name: ${device_upper} BRAND
  lambda: return {"Lolin"};
  update_interval: 7d
  entity_category: diagnostic
- platform: template
  name: ${device_upper} HARDWARE
  lambda: return {"C3 Mini"};
  update_interval: 7d
  entity_category: diagnostic
- platform: template
  name: ${device_upper} PERIPHERALS
  lambda: return {""};
  update_interval: 7d
  entity_category: diagnostic
- platform: version
  name: ${device_upper} SOFTWARE
  entity_category: diagnostic
- platform: wifi_info
  ip_address:
    name: ${device_upper} IP
  mac_address:
    name: ${device_upper} MAC

sensor:
- platform: wifi_signal
  name: ${device_upper} WiFi Signal
  update_interval: 30s
- platform: uptime
  update_interval: 30s
  name: ${device_upper} Uptime
button:
- platform: restart
  name: ${device_upper} RESTART

output:
- platform: ledc
  id: motor_forward_pin
  pin: GPIO5
- platform: ledc
  id: motor_reverse_pin
  pin: GPIO4

fan:
- platform: hbridge
  name: "Kitchen Fan"
  pin_a: motor_forward_pin
  pin_b: motor_reverse_pin
