esphome:
  name: garage-opener-d1

esp8266:
  board: d1_mini
  framework:
    version: recommended

ota:
  safe_mode: true
# password:

api:

logger:

captive_portal:

web_server:
  port: 80

wifi:
  # ssid: 
  # password:
  ap:
    ssid: "Garage Door Opener"

switch:
  - platform: gpio
    pin: 
      number: GPIO0 # to switch 4
      inverted: true
    id: remote_bike_manual
    name: "Bike Remote Manual"
    icon: "mdi:bike"
    on_turn_on:
    - delay: 300ms
    - switch.turn_off: remote_bike_manual
  - platform: gpio
    pin: 
      number: GPIO2 # to switch 2
      inverted: true
    id: remote_car_manual
    name: "Car Remote Manual"
    icon: "mdi:car"
    on_turn_on:
    - delay: 300ms
    - switch.turn_off: remote_car_manual
button:
  - platform: template
    name: Car door remote
    id: car_remote_button
    # Optional variables:
    icon: "mdi:tools"
    on_press:
    - switch.turn_on: remote_car_manual
  - platform: template
    name: bike door remote
    id: bike_remote_button
    # Optional variables:
    icon: "mdi:bike"
    on_press:
    - switch.turn_on: remote_bike_manual
  - platform: template
    name: Open both bike and car doors
    id: remote_open_both_garage_door
    icon: "mdi:garage"
    on_press:
    - switch.turn_on: remote_bike_manual
    - delay: 2s
    - switch.turn_on: remote_car_manual
