esphome:
  name: link
  friendly_name: link
  on_boot:
    priority: -100.0
    then:
      - lambda: |-
          ESP_LOGD("custom", "Sending 0x11 (Sleep Out) command to display");
          id(my_oled_display).command(0x11);
  platformio_options:
    build_flags:
      - "-Dprotected=public"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino # REQUIRED for SSD1351 display

# Enable logging
logger:

# Enable Home Assistant API
api:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome
  password: !secret ota_password

font:
  - file: "gfonts://Roboto"
    id: my_font
    size: 12

spi:
  - id: spi_bus_display
    clk_pin: 7
    mosi_pin: 8

display:
  - platform: ssd1351_spi
    id: my_oled_display
    model: "SSD1351_128X128"
    spi_id: spi_bus_display
    cs_pin: 6
    dc_pin: 5
    reset_pin: 4
    brightness: 100%
    lambda: |-
      it.print(0, 0, id(my_font), "Hello again!");

button:
  - platform: restart
    name: "Restart"

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    name: "screen right button GPIO 0"
  - platform: gpio
    pin:
      number: 9
      mode: INPUT_PULLUP
      inverted: true
    name: "cross top button GPIO 9"
  - platform: gpio
    pin:
      number: 10
      mode: INPUT_PULLUP
      inverted: true
    name: "cross right button GPIO 10"
  - platform: gpio
    pin:
      number: 11
      mode: INPUT_PULLUP
      inverted: true
    name: "cross bottom button GPIO 11"
  - platform: gpio
    pin:
      number: 12
      mode: INPUT_PULLUP
      inverted: true
    name: "cross left button GPIO 12"
  - platform: gpio
    pin:
      number: 13
      mode: INPUT_PULLUP
      inverted: true
    name: "right a button GPIO 13"
  - platform: gpio
    pin:
      number: 14
      mode: INPUT_PULLUP
      inverted: true
    name: "right b button GPIO 14"
  - platform: gpio
    pin:
      number: 17
      mode: INPUT_PULLUP
      inverted: true
    name: "screen left button GPIO 17"