esphome:
  name: link
  friendly_name: link

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino # Changed from esp-idf for hub75 display compatibility

# Enable logging
logger:

# Enable Home Assistant API
api:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome
  password: !secret ota_password

font:
  - file: "gfonts://Roboto"
    id: my_font
    size: 12

spi:
  - id: spi_bus_display
    clk_pin: 16
    mosi_pin: 15

display:
  - platform: ssd1351_spi
    model: "SSD1351_128X128"
    spi_id: spi_bus_display
    cs_pin: 18
    dc_pin: 19
    reset_pin: 21
    lambda: |-
      it.print(0, 0, id(my_font), "Hello again!");

button:
  - platform: restart
    name: "Restart"

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    name: "screen right button GPIO 0"
  - platform: gpio
    pin:
      number: 9
      mode: INPUT_PULLUP
      inverted: true
    name: "cross top button GPIO 9"
  - platform: gpio
    pin:
      number: 10
      mode: INPUT_PULLUP
      inverted: true
    name: "cross right button GPIO 10"
  - platform: gpio
    pin:
      number: 11
      mode: INPUT_PULLUP
      inverted: true
    name: "cross bottom button GPIO 11"
  - platform: gpio
    pin:
      number: 12
      mode: INPUT_PULLUP
      inverted: true
    name: "cross left button GPIO 12"
  - platform: gpio
    pin:
      number: 13
      mode: INPUT_PULLUP
      inverted: true
    name: "right a button GPIO 13"
  - platform: gpio
    pin:
      number: 14
      mode: INPUT_PULLUP
      inverted: true
    name: "right b button GPIO 14"
  - platform: gpio
    pin:
      number: 17
      mode: INPUT_PULLUP
      inverted: true
    name: "screen left button GPIO 17"
