esphome:
  name: myq
  
esp8266:
  board: d1_mini
  framework:
    version: recommended

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  safe_mode: true
  password: !secret ota_password

mqtt:
  broker: !secret mqtt_broker_ip

api:

# logger:

switch:
  - platform: gpio
    pin: 
      number: D1
      inverted: true
    id: remote_garage_manual
    name: "Garage Remote Manual"
    icon: "mdi:garage"
    on_turn_on:
    - delay: 200ms
    - switch.turn_off: remote_garage_manual
  - platform: gpio
    pin: 
      number: D4
      inverted: true
    id: remote_workshop_manual
    name: "Workshop Remote Manual"
    icon: "mdi:garage"
    on_turn_on:
    - delay: 200ms
    - switch.turn_off: remote_workshop_manual
button:
  - platform: template
    name: Workshop door remote
    id: workshop_remote_button
    # Optional variables:
    icon: "mdi:tools"
    on_press:
    - switch.turn_on: remote_workshop_manual
  - platform: template
    name: garage door remote
    id: garage_remote_button
    # Optional variables:
    icon: mdi:garage"
    on_press:
    - switch.turn_on: remote_garage_manual
  - platform: template
    name: Open both garage doorgarage door remote
    id: remote_open_both_garage_door
    icon: mdi:bike"
    on_press:
    - switch.turn_on: remote_garage_manual
    - delay: 2s
    - switch.turn_on: remote_workshop_manual
