esphome:
  name: myq
esp8266:
  board: d1_mini
  framework:
    version: recommended
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  safe_mode: true
  password: !secret ota_password

mqtt:
  broker: !secret mqtt_broker_ip

api:

# logger:

output:
  - platform: gpio
    pin: 
      number: D1
      inverted: true
    id: remote_garage_sw1_press
  - platform: gpio
    pin: 
      number: D4
      inverted: true
    id: remote_garage_sw4_press

button:
  - platform: template
    name: Garage door remote
    id: remote_garage_door_button
    icon: "mdi:garage"
    on_press:
    - output.turn_on: remote_garage_sw1_press
    - delay: 200ms
    - output.turn_off: remote_garage_sw1_press
  - platform: template
    name: Workshop door remote
    id: remote_workshop_door_button
    icon: "mdi:tools"
    on_press:
    - output.turn_on: remote_garage_sw4_press
    - delay: 200ms
    - output.turn_off: remote_garage_sw4_press
  - platform: template
    name: Press both garage doors buttons
    id: remote_both_garage_doors_buttons
    icon: "mdi:bike"
    on_press:
    - output.turn_on: remote_garage_sw1_press
    - delay: 200ms
    - output.turn_off: remote_garage_sw1_press        
    - delay: 2s
    - output.turn_on: remote_garage_sw4_press
    - delay: 200ms
    - output.turn_off: remote_garage_sw4_press