esphome:
  name: myq

esp8266:
  board: d1_mini
  framework:
    version: recommended

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  safe_mode: true
  password: !secret ota_password

mqtt:
  broker: !secret mqtt_broker_ip

api:

logger:

switch:
  - platform: gpio
    pin: 
      number: D1
      inverted: true
    id: remote_garage_manual
    name: "Garage Remote Manual"
    icon: "mdi:garage"
    on_turn_on:
    - delay: 300ms
    - switch.turn_off: remote_garage_manual
  - platform: gpio
    pin: 
      number: D4
      inverted: true
    id: remote_workshop_manual
    name: "Workshop Remote Manual"
    icon: "mdi:garage"
    on_turn_on:
    - delay: 300ms
    - switch.turn_off: remote_workshop_manual
  - platform: template
    id: remote_both_garage_doors
    name: Virtual button for both garage doors
    turn_on_action:
      - switch.turn_on: remote_workshop_manual
      - delay: 1s
      - switch.turn_on: remote_garage_manual
      - delay: 1s
      - switch.turn_off: remote_both_garage_doors

button:
  - platform: template
    name: Workshop door remote
    id: workshop_remote_button
    # Optional variables:
    icon: "mdi:tools"
    on_press:
    - switch.turn_on: remote_workshop_manual
  - platform: template
    name: garage door remote
    id: garage_remote_button
    # Optional variables:
    icon: "mdi:garage"
    on_press:
    - switch.turn_on: remote_garage_manual
  - platform: template
    name: Press both garage door buttons
    id: remote_toggle_both_garage_doors
    icon: "mdi:bike"
    on_press:
    - switch.turn_on: remote_workshop_manual
    - delay: 1s
    - switch.turn_on: remote_garage_manual
