substitutions:
  device_name: "ebike-g1-charger" # Define the base name for your device

# Global variables hold learned and configured values that persist across reboots.
globals:
  - id: peak_power_learned
    type: float
    restore_value: yes
    initial_value: '0.0'
  - id: charge_session_start_energy
    type: float
    restore_value: yes
    initial_value: '0.0'
  - id: is_stabilizing
    type: bool
    restore_value: no
    initial_value: 'false'
  # --- New globals to store persistent battery configuration ---
  - id: battery_nominal_voltage_g
    type: float
    restore_value: yes
    initial_value: '48.0' # Default to 48V, change if needed
  - id: battery_capacity_ah_g
    type: float
    restore_value: yes
    initial_value: '10.0' # Default to 10Ah, change if needed
  - id: last_session_percentage_added
    type: float
    restore_value: yes
    initial_value: '0.0'

# Basic Config
esp8266:
  board: esp01_1m

esphome:
  name: ${device_name}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "esphome_${device_name}"

captive_portal:

# Home Assistant Integration
api:

ota:
  platform: esphome

web_server:
  port: 80

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

# This script manages the 60-second stabilization period.
script:
  - id: start_charge_sequence
    mode: single # Ensures only one instance of this script can run at a time.
    then:
      - globals.set:
          id: is_stabilizing
          value: 'true'
      - logger.log: "Charger ON. Stabilization period started (1 minute)."
      - delay: 120s
      - globals.set:
          id: is_stabilizing
          value: 'false'
      - logger.log: "Stabilization period ended. Power monitoring is now active."

# ---------------------------------------------------
# --- SENSORS & INPUTS
# ---------------------------------------------------

# User-configurable values that will show up as sliders/boxes in Home Assistant/ESPHome UI
number:
  - platform: template
    id: shutdown_threshold_w
    name: "Manual Shutdown Threshold"
    optimistic: true
    min_value: 0
    max_value: 500 # Adjust based on your charger's max power
    step: 1.0
    unit_of_measurement: "W"
    icon: "mdi:power-plug-off"
  # --- These number inputs now read from and write to the persistent globals ---
  - platform: template
    name: "Battery Nominal Voltage"
    icon: "mdi:bike"
    unit_of_measurement: "V"
    min_value: 12
    max_value: 84
    step: 0.1
    lambda: 'return id(battery_nominal_voltage_g);'
    set_action:
      - globals.set:
          id: battery_nominal_voltage_g
          value: !lambda 'return x;'
  - platform: template
    name: "Battery Capacity"
    icon: "mdi:battery-plus"
    unit_of_measurement: "Ah"
    min_value: 1
    max_value: 50
    step: 0.1
    lambda: 'return id(battery_capacity_ah_g);'
    set_action:
      - globals.set:
          id: battery_capacity_ah_g
          value: !lambda 'return x;'

sensor:
  # Power Monitoring Sensor
  - platform: cse7766
    power:
      name: "${device_name} Power"
      accuracy_decimals: 2
      id: power
      filters:
        - throttle_average: 5s
      on_value:
        - if:
            condition:
              and:
                - switch.is_on: relay
                - lambda: 'return !id(is_stabilizing);'
                - lambda: 'return id(power).state > 10.0;'
            then:
              - if:
                  condition:
                    lambda: 'return id(power).state > id(peak_power_learned);'
                  then:
                    - globals.set:
                        id: peak_power_learned
                        value: !lambda 'return id(power).state;'
                    - logger.log: "New peak power learned."
              - if:
                  condition:
                    and:
                      - lambda: 'return id(peak_power_learned) > 30.0;'
                      - lambda: 'return id(power).state < (id(peak_power_learned) * 0.85);'
                  then:
                    - logger.log: "Charge complete: Power draw has decreased. Turning off."
                    - switch.turn_off: relay
        - if:
            condition:
              and:
                - switch.is_on: relay
                - lambda: 'return !id(is_stabilizing);'
                - lambda: 'return id(shutdown_threshold_w).state > 0;'
                - lambda: 'return id(power).state < id(shutdown_threshold_w).state;'
            then:
              - logger.log: "Charge complete: Power is below manual threshold. Turning off."
              - switch.turn_off: relay
    voltage:
      name: "${device_name} Voltage"
      accuracy_decimals: 2
    current:
      name: "${device_name} Current"
      accuracy_decimals: 2
    energy:
      name: "${device_name} Energy"
      id: total_energy
      accuracy_decimals: 3

  - platform: template
    name: "Learned Peak Power"
    id: learned_peak_power_sensor
    lambda: 'return id(peak_power_learned);'
    unit_of_measurement: "W"
    icon: "mdi:chart-line-variant"
    update_interval: 15s

  - platform: template
    name: "Energy Added This Session"
    id: energy_added_this_session
    unit_of_measurement: "Wh"
    accuracy_decimals: 1
    icon: "mdi:flash"
    update_interval: 15s
    lambda: |-
      if (id(relay).state) {
        float energy_kwh = id(total_energy).state - id(charge_session_start_energy);
        return energy_kwh * 1000.0;
      } else {
        return 0.0;
      }

  # --- New sensor to display the percentage added during the last completed session ---
  - platform: template
    name: "Percentage Added Last Session"
    id: percentage_added_last_session
    unit_of_measurement: "%"
    accuracy_decimals: 1
    icon: "mdi:battery-arrow-up"
    lambda: 'return id(last_session_percentage_added);'


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${device_name} Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${device_name} Status"
  - platform: template
    name: "E-Bike Charging"
    id: charging_status
    device_class: power
    lambda: 'return id(relay).state;'

# ---------------------------------------------------
# --- SWITCHES & CONTROLS
# ---------------------------------------------------

switch:
  - platform: gpio
    name: "${device_name} Relay"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - globals.set:
          id: charge_session_start_energy
          value: !lambda 'return id(total_energy).state;'
      - script.execute: start_charge_sequence
    # When the relay is turned OFF...
    on_turn_off:
      - logger.log: "Charger turned OFF."
      - script.stop: start_charge_sequence
      - globals.set:
          id: is_stabilizing
          value: 'false'
      # --- New action to calculate and store the percentage added ---
      - lambda: |-
          float total_wh = id(battery_nominal_voltage_g) * id(battery_capacity_ah_g);
          if (total_wh > 0) {
            float energy_this_session_kwh = id(total_energy).state - id(charge_session_start_energy);
            float energy_this_session_wh = energy_this_session_kwh * 1000.0;
            
            // Assume 90% charger efficiency
            float energy_into_battery_wh = energy_this_session_wh * 0.90;

            float percentage = (energy_into_battery_wh / total_wh) * 100.0;
            id(last_session_percentage_added) = fmin(100.0, fmax(0.0, percentage));
          } else {
            id(last_session_percentage_added) = 0.0;
          }

  - platform: template
    name: "Reset Peak Power"
    id: reset_peak_power
    icon: "mdi:refresh"
    optimistic: true
    on_turn_on:
      - logger.log: "Peak power manually reset by user."
      - globals.set:
          id: peak_power_learned
          value: '0.0'
      - delay: 1s
      - switch.turn_off: reset_peak_power

status_led:
  pin:
    number: GPIO13
    inverted: True
