esphome:
  name: bed0

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  safe_mode: true
  password: !secret ota_password

mqtt:
  broker: !secret mqtt_broker_ip

api:

logger:

includes:
  - hx711_dualchannel.h

sensor:
  - platform: custom
    lambda: |-
class MyCustomSensor : public PollingComponent {
 public:
  Adafruit_BMP085 bmp;
  Sensor *weight_chan_a = new Sensor();
  Sensor *weithp_chan_b = new Sensor();

  MyCustomSensor() : PollingComponent(15000) { }

  void setup() override {
    bmp.begin();
  }

  void update() override {
    // This is the actual sensor reading logic.
    float temperature = bmp.readTemperature();
    temperature_sensor->publish_state(temperature);

    int pressure = bmp.readPressure();
    pressure_sensor->publish_state(pressure / 100.0);
  }
};
  - platform: hx711
    name: "bed_presence_window"
    dout_pin: D0
    clk_pin: D1
    gain: 64
    update_interval: 10s
    filters:
      - calibrate_linear:
        - 46800 -> 0
        - 58527 -> 70
    unit_of_measurement: kg
#  - platform: hx711
#    name: "bed_presence_wall"
#    dout_pin: D0
#    clk_pin: D1
#    gain: 32
#    update_interval: 5s
#    filters:
#      - calibrate_linear:
#        - 9800 -> 0
#        - 18000 -> 70
#    unit_of_measurement: kg
