substitutions:
  name: esp433-c3

esphome:
  name: ${name}

esp32:
  board: lolin_c3_mini
#  framework:
#    type: arduino

logger:
  level: DEBUG
  baud_rate: 0 # (No need for UART logging)

ota:
  platform: esphome
  #  safe_mode: true
# password:

#captive_portal:

#web_server:
#  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 8.5

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: "${device_name} WiFi SSID"
    bssid:
      name: "${device_name} Access Point MAC Address"
sensor:
  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 60s
api:
  services:
    - service: send_rf_code_etek
      variables:
        rcswitch_code: string
      then:
        - remote_transmitter.transmit_rc_switch_raw:
            code: !lambda "return rcswitch_code;"
            protocol: 7 #!lambda 'return esphome::remote_base::RC_SWITCH_PROTOCOLS[rcswitch_protocol];'
    - service: send_rf_code_jjx
      variables:
        rcswitch_code: string
      then:
        - remote_transmitter.transmit_rc_switch_raw:
            code: !lambda "return rcswitch_code;"
            protocol: 1 #!lambda 'return esphome::remote_base::RC_SWITCH_PROTOCOLS[rcswitch_protocol];
remote_transmitter:
  pin: GPIO10
  carrier_duty_percent: 100%
  rmt_channel: 0

remote_receiver:
  pin: GPIO3
  dump: all
  #  - rc_switch
  tolerance: 50%
  filter: 250us
  idle: 4ms
  buffer_size: 2kb
  rmt_channel: 2
