esphome:
  name: heatpump_controller_esphome
  comment: Mitsubishi Heat Pump controller

esp32:
  board: lolin_c3_mini
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  safe_mode: true
  password: !secret ota_password

mqtt:
  broker: !secret mqtt_broker_ip

api:

logger:
  level: INFO
  baud_rate: 0

external_components:
  - source: github://geoffdavis/esphome-mitsubishiheatpump