esphome:
  name: keypad

esp8266:
  board: d1_mini
  framework:
    version: recommended

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  safe_mode: true
  password: !secret ota_password

mqtt:
  broker: !secret mqtt_broker_ip

api:

logger:

binary_sensor:
  - platform: gpio
    pin: D0
    name: "d0"
  - platform: gpio
    pin: D1
    name: "d1"
  - platform: gpio
    pin: D2
    name: "d2"
  - platform: gpio
    pin: D3
    name: "d3"
